name: Build and Deploy to Cloud Run (WIF)

on:
  push:
    branches: ["WIF"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/183355380557/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github@project-seekho.iam.gserviceaccount.com"

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and Push
        id: build
        run: |
          IMAGE=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-app:${GITHUB_SHA}
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          docker build -t $IMAGE .
          docker push $IMAGE

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Authenticate with WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/183355380557/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-deployer@PROJECT_ID.iam.gserviceaccount.com"

      - name: Deploy to Cloud Run
        run: |
          IMAGE=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-app:${GITHUB_SHA}
          gcloud run deploy my-service-dev \
            --image $IMAGE \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
